In [1]:
import sys
import os
sys.path.append(os.path.abspath("../src"))

from battle_cat_calc.models import GachaSlot, Position, Track, GachaPool, GachaStep
from battle_cat_calc.simulator import GachaSimulator
from battle_cat_calc.fetcher import BCDataFetcher
from battle_cat_calc.parser import BCParser

from tqdm.notebook import tqdm

import pandas as pd

In [2]:
# Params

max_roll = 200

In [3]:
# PoolA

# 抓取資料
fetcher_a = BCDataFetcher()
html_a = await fetcher_a.fetch_html(seed="2127986414", event="2025-12-12_1019", lang="tw", count=max_roll)

# 解析
parser_a = BCParser(html_a)
track_a = parser_a.track_a
track_b = parser_a.track_b

# 建立池
pool_a = GachaPool(
    pool_id="2025-12-12_1019",
    name="2025-12-12 ~ 2025-12-22: 全新傳說稀有和超激稀有角色參戰！新世紀福音戰士合作轉蛋登場！",
    track_a=track_a,
    track_b=track_b,
    has_guaranteed=True
)

display(pd.DataFrame(track_a))
display(pd.DataFrame(track_b))

,id,result,guaranteed,next_pos,original_result,original_guaranteed,is_duplicate_rare
0,"{'id': 1, 'track': 'A'}",貓咪陰陽師,第10使徒,"{'id': 11, 'track': 'B'}",None,None,False
1,"{'id': 2, 'track': 'A'}",拳擊手貓,白夜姬零,"{'id': 12, 'track': 'B'}",None,None,False
2,"{'id': 3, 'track': 'A'}",搖滾貓,第6使徒,"{'id': 13, 'track': 'B'}",None,None,False
3,"{'id': 4, 'track': 'A'}",神槍手貓,EVA量產機,"{'id': 14, 'track': 'B'}",None,None,False
4,"{'id': 5, 'track': 'A'}",占卜貓,EVA零號機,"{'id': 15, 'track': 'B'}",None,None,False
...,...,...,...,...,...,...,...
195,"{'id': 196, 'track': 'A'}",放浪貓弟,,None,None,None,False
196,"{'id': 197, 'track': 'A'}",擊劍貓,,None,None,None,False
197,"{'id': 198, 'track': 'A'}",暖桌貓,,None,None,None,False
198,"{'id': 199, 'track': 'A'}",魔劍士貓,,None,None,None,False
199,"{'id': 200, 'track': 'A'}",侏羅貓,,None,None,None,False

,id,result,guaranteed,next_pos,original_result,original_guaranteed,is_duplicate_rare
0,"{'id': 1, 'track': 'B'}",貓咪陰陽師,白夜姬零,"{'id': 12, 'track': 'B'}",None,None,False
1,"{'id': 2, 'track': 'B'}",明日香貓,第6使徒,"{'id': 13, 'track': 'B'}",None,None,False
2,"{'id': 3, 'track': 'B'}",車輪貓,EVA量產機,"{'id': 14, 'track': 'B'}",None,None,False
3,"{'id': 4, 'track': 'B'}",薰貓,EVA零號機,"{'id': 15, 'track': 'B'}",None,None,False
4,"{'id': 5, 'track': 'B'}",御宅貓,EVA初號機,"{'id': 16, 'track': 'B'}",None,None,False
...,...,...,...,...,...,...,...
195,"{'id': 196, 'track': 'B'}",薰貓,,None,None,None,False
196,"{'id': 197, 'track': 'B'}",拳擊手貓,,None,None,None,False
197,"{'id': 198, 'track': 'B'}",搖滾貓,,None,None,None,False
198,"{'id': 199, 'track': 'B'}",侏羅貓,,None,None,None,False
199,"{'id': 200, 'track': 'B'}",零貓,,None,None,None,False

In [4]:
# Pool B

# 抓取資料
fetcher_b = BCDataFetcher()
html_b = await fetcher_b.fetch_html(seed="2127986414", event="2025-12-12_1020", lang="tw", count=max_roll)

# 解析
parser_b = BCParser(html_b)
track_a = parser_b.track_a
track_b = parser_b.track_b

# 建立池
pool_b = GachaPool(
    pool_id="2025-12-12_1020",
    name="2025-12-12 ~ 2025-12-22: 全新傳說稀有角色參戰！新世紀福音戰士合作轉蛋2nd登場！",
    track_a=track_a,
    track_b=track_b,
    has_guaranteed=True
)

display(pd.DataFrame(track_a))
display(pd.DataFrame(track_b))

,id,result,guaranteed,next_pos,original_result,original_guaranteed,is_duplicate_rare
0,"{'id': 1, 'track': 'A'}",貓咪陰陽師,第9使徒,"{'id': 11, 'track': 'B'}",None,None,False
1,"{'id': 2, 'track': 'A'}",拳擊手貓,獨眼少女明日香,"{'id': 12, 'track': 'B'}",None,None,False
2,"{'id': 3, 'track': 'A'}",搖滾貓,獨眼少女明日香,"{'id': 13, 'track': 'B'}",None,None,False
3,"{'id': 4, 'track': 'A'}",神槍手貓,EVA第13號機,"{'id': 14, 'track': 'B'}",None,None,False
4,"{'id': 5, 'track': 'A'}",占卜貓,通訊聯絡機零月,"{'id': 15, 'track': 'B'}",None,None,False
...,...,...,...,...,...,...,...
195,"{'id': 196, 'track': 'A'}",放浪貓弟,,None,None,None,False
196,"{'id': 197, 'track': 'A'}",擊劍貓,,None,None,None,False
197,"{'id': 198, 'track': 'A'}",暖桌貓,,None,None,None,False
198,"{'id': 199, 'track': 'A'}",魔劍士貓,,None,None,None,False
199,"{'id': 200, 'track': 'A'}",侏羅貓,,None,None,None,False

,id,result,guaranteed,next_pos,original_result,original_guaranteed,is_duplicate_rare
0,"{'id': 1, 'track': 'B'}",貓咪陰陽師,獨眼少女明日香,"{'id': 12, 'track': 'B'}",None,None,False
1,"{'id': 2, 'track': 'B'}",明日香貓,獨眼少女明日香,"{'id': 13, 'track': 'B'}",None,None,False
2,"{'id': 3, 'track': 'B'}",車輪貓,EVA第13號機,"{'id': 14, 'track': 'B'}",None,None,False
3,"{'id': 4, 'track': 'B'}",薰貓,通訊聯絡機零月,"{'id': 15, 'track': 'B'}",None,None,False
4,"{'id': 5, 'track': 'B'}",御宅貓,EVA8號機,"{'id': 16, 'track': 'B'}",None,None,False
...,...,...,...,...,...,...,...
195,"{'id': 196, 'track': 'B'}",薰貓,,None,None,None,False
196,"{'id': 197, 'track': 'B'}",拳擊手貓,,None,None,None,False
197,"{'id': 198, 'track': 'B'}",搖滾貓,,None,None,None,False
198,"{'id': 199, 'track': 'B'}",侏羅貓,,None,None,None,False
199,"{'id': 200, 'track': 'B'}",零貓,,None,None,None,False

In [5]:
# 模擬
sim = GachaSimulator([
    pool_a, 
    pool_b
])

targets = set([
    '月影少年薰',
    'EVA量產機',
    'EVA零號機',
    'EVA初號機',
    '真嗣貓',
    '白夜姬零',
    '第6使徒',
    '第10使徒',
    'EVA2號機',
    '通訊聯絡機零月',
    'EVA8號機',
    '空中戰艦貓咪Wunder',   
    '第4使徒',
    '第9使徒',
    '獨眼少女明日香',
    'EVA第13號機',
    '小小零',
    '小小明日香',
    '小小美里',
    '小小真理',
    '小小律子',
    '小小綾波零（暫稱）',
    '零貓',
    '明日香貓',
    '真理貓',
    '薰貓'
])

import time
pbar = tqdm(total=max_roll, desc="Find Best Path", unit="rolls")
last_cost = 0
last_time = time.time()
last_processed = 0

def update_progress(cost, processed, queue):
    global last_cost, last_time, last_processed
    now = time.time()
    # 每 2 秒或 cost 增加時更新進度條
    if cost > last_cost:
        pbar.update(cost - last_cost)
        last_cost = cost
    if now - last_time >= 2:
        speed = (processed - last_processed) / (now - last_time)
        pbar.set_postfix({
            "狀態數": processed,
            "佇列": queue,
            "速率": f"{speed:.0f} st/s",
            "cost": cost,
        })
        last_time = now
        last_processed = processed

result = sim.find_best_path(
    Position(1, 'A'), 
    targets, 
    max_rolls=250,
    progress_callback=update_progress,
    # beam_width = 30000
)
pbar.close()
# 顯示結果
print(result.to_summary())

Find Best Path:   0%|          | 0/200 [00:00<?, ?rolls/s]

=== 模擬結果 ===
總花費: 119 抽
路徑步數: 38 (單抽 29, 十連 9)
收集到: EVA2號機, EVA8號機, EVA初號機, EVA第13號機, EVA量產機, EVA零號機, 小小律子, 小小明日香, 小小真理, 小小綾波零（暫稱）, 小小美里, 小小零, 明日香貓, 月影少年薰, 獨眼少女明日香, 白夜姬零, 真嗣貓, 真理貓, 空中戰艦貓咪Wunder, 第10使徒, 第4使徒, 第6使徒, 第9使徒, 薰貓, 通訊聯絡機零月, 零貓
使用池子: 2025-12-12_1019, 2025-12-12_1020
起點: Position(id=1, track='A') → 終點: Position(id=125, track='A')

=== 路徑詳情 ===
1. [2025-12-12_1019] 1A → 2A: 貓咪陰陽師 (單抽)
2. [2025-12-12_1019] 2A → 12B: 白夜姬零 (十連) (跳軌)
3. [2025-12-12_1019] 12B → 13B: 快泳貓 (單抽)
4. [2025-12-12_1019] 13B → 14B: 魔女貓 (單抽)
5. [2025-12-12_1019] 14B → 15B: 放浪貓弟 (單抽)
6. [2025-12-12_1019] 15B → 26A: 第6使徒 (十連) (跳軌)
7. [2025-12-12_1019] 26A → 27A: 真理貓 (單抽)
8. [2025-12-12_1019] 27A → 28A: 貓咪陰陽師 (單抽)
9. [2025-12-12_1019] 28A → 29A: 美容貓 (單抽)
10. [2025-12-12_1019] 29A → 30A: 貓咪探測器 (單抽)
11. [2025-12-12_1019] 30A → 31A: 美容貓 (單抽)
12. [2025-12-12_1019] 31A → 32A: 海賊貓 (單抽)
13. [2025-12-12_1019] 32A → 33A: 美容貓 (單抽)
14. [2025-12-12_1019] 33A → 34A: 神槍手貓 (單抽)
15. [2025-12-12_1019] 34A → 35A: 侏羅貓 (單抽)
16. [2025-12-12_1019] 35A → 36A: 貓咪陰陽師 (單抽)
17. [2025-12-12_1020] 36A → 37A: 拳擊手貓 (單抽)
18. [2025-12-12_1019] 37A → 38A: 弓箭手貓 (單抽)
19. [2025-12-12_1020] 38A → 39A: 薩滿貓 (單抽)
20. [2025-12-12_1020] 39A → 40A: 小小綾波零（暫稱） (單抽)
21. [2025-12-12_1019] 40A → 41A: 麵包機貓 (單抽)
22. [2025-12-12_1019] 41A → 42A: 魔劍士貓 (單抽)
23. [2025-12-12_1019] 42A → 43A: 貓咪陰陽師 (單抽)
24. [2025-12-12_1020] 43A → 53B: 通訊聯絡機零月 (十連) (跳軌)
25. [2025-12-12_1019] 53B → 64A: EVA量產機 (十連) (跳軌)
26. [2025-12-12_1019] 64A → 65A: 冰刀二人組 (單抽)
27. [2025-12-12_1019] 65A → 66A: 小偷貓 (單抽)
28. [2025-12-12_1019] 66A → 76B: EVA零號機 (十連) (跳軌)
29. [2025-12-12_1019] 76B → 77B: 車輪貓 (單抽)
30. [2025-12-12_1020] 77B → 78B: 小小真理 (單抽)
31. [2025-12-12_1019] 78B → 79B: 鬥牛士貓 (單抽)
32. [2025-12-12_1019] 79B → 80B: 真理貓 (單抽)
33. [2025-12-12_1019] 80B → 81B: 小偷貓 (單抽)
34. [2025-12-12_1019] 81B → 92A: EVA初號機 (十連) (跳軌)
35. [2025-12-12_1020] 92A → 103A: EVA8號機 (十連) (跳軌)
36. [2025-12-12_1019] 103A → 104A: 高蹺貓 (單抽)
37. [2025-12-12_1019] 104A → 114B: 真嗣貓 (十連) (跳軌)
38. [2025-12-12_1020] 114B → 125A: 第9使徒 (十連) (跳軌)

In [6]:
result

GachaResult(cost=119, steps=38, collected=26)